model:
  config_path: "/mnt/bn/pistis/fangyan/workdir/mllm-codebase/VeOmni/configs/model_configs/qwen/Qwen3-0.6B.json"
  attn_implementation: sdpa
  tokenizer_path: "/mnt/bn/pistis/fangyan/model_ckpts/Qwen2.5-VL-7B-Instruct"
  pretrained_weights: "/mnt/bn/pistis/fangyan/model_ckpts/Qwen3-0.6B"
  tokenizer: "/mnt/bn/pistis/fangyan/model_ckpts/Qwen3-0.6B"
  image_processor: "/mnt/bn/pistis/fangyan/workdir/LLaVA-NeXT/checkpoints/siglip2-so400m-patch16-384"
  use_flex_attn: true

data:
  # train_path: "/mnt/bn/zilongdata-us/dataset/recap-datacomp-1b-webdataset/{000000..124249}.tar"
  train_path: "/mnt/bn/zilongdata-us/dataset/recap-datacomp-1b-webdataset/{000000..124249}.tar"
  source_name: "recap_datacomp_1b"
  chat_template: qwen2vl_pretrain
  train_size: 610_000_000_000 # 166_400_000_000 estimated for 256M samples, with avg 650 tokens/sample
  dataloader_type: native
  datasets_type: iterable_wds
  num_workers: 8
  max_seq_len: 16384 # next 131,072
  drop_last: true

train:
  output_dir: /mnt/bn/pistis/fangyan/exps/ViT-Speak-Qwen3-0.6B-Cap1B
  step2token_path: /mnt/bn/pistis/fangyan/exps/ViT-Speak-Qwen3-0.6B-Cap1B
  data_parallel_mode: fsdp1
  micro_batch_size: 16
  # global_batch_size: 512
  bsz_warmup_ratio: 0.0
  rmpad: false
  rmpad_with_pos_ids: true
  optimizer: adamw
  max_grad_norm: 1.0
  lr: 1e-3
  lr_warmup_ratio: 0.007
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  weight_decay: 0.01
  enable_gradient_checkpointing: true
  init_device: cpu
  max_steps: 100000
  save_steps: 10000
  save_hf_weights: true
  # use_wandb: true
  use_wandb: false
  enable_mixed_precision: true
  # freeze_lm_head: true
  # wandb_project: mllm-dev-fy
  wandb_project: vit-mllm
  wandb_name: ViT-Speak-Qwen3-0.6B-Cap1B
  
